theme: jekyll-theme-minimal

# Site identity
title: Tianrun Zhao
description: ""

# Optional (recommended on GitHub Pages):
# url: https://YOUR_USERNAME.github.io
# baseurl: ""

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
